#!/usr/bin/env python3
"""
ReFix EOS v3 - ABI table generator.

Parses the vendored official EOS SDK C headers and emits
`src/eossdk/gen/eos_export_table.inc`, a compile-time description of every
export in `src/eos_export_names.txt`:

  * ordinal (must match src/eos_fwd.asm / src/eos_proxy.def)
  * canonical name
  * return kind  (what a *safe* default return value looks like)
  * async kind   (does it take a completion delegate we must answer?)

Nothing about the emulator's behaviour is hardcoded here: the classification is
derived from the SDK headers themselves, so adding a newer SDK drop and
re-running this script is all that is required to track new APIs.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SDK  = os.path.join(ROOT, 'src', 'eossdk', 'sdk')
NAMES= os.path.join(ROOT, 'src', 'eos_export_names.txt')
OUT  = os.path.join(ROOT, 'src', 'eossdk', 'gen', 'eos_export_table.inc')

DECL = re.compile(r'EOS_DECLARE_FUNC\(\s*(.*?)\s*\)\s*([A-Za-z_][A-Za-z0-9_]*)\s*\((.*?)\)\s*;', re.S)

def parse_headers():
    fns = {}
    for fn in sorted(os.listdir(SDK)):
        if not fn.endswith('.h'):
            continue
        text = open(os.path.join(SDK, fn), encoding='utf-8', errors='replace').read()
        text = re.sub(r'/\*.*?\*/', ' ', text, flags=re.S)
        text = re.sub(r'//[^\n]*', ' ', text)
        for m in DECL.finditer(text):
            ret, name, params = m.group(1), m.group(2), m.group(3)
            params = [p.strip() for p in params.split(',') if p.strip()]
            fns[name] = (ret.strip(), params, fn)
    return fns

def return_kind(ret, name):
    r = ret.replace('const', '').strip()
    if r == 'void':                       return 'RK_VOID'
    if r == 'EOS_EResult':                return 'RK_RESULT'
    if r == 'EOS_NotificationId':         return 'RK_NOTIFY'
    if r == 'EOS_Bool':                   return 'RK_BOOL'
    if r.endswith('*'):                   return 'RK_PTR'
    if r in ('EOS_ProductUserId', 'EOS_EpicAccountId', 'EOS_ContinuanceToken'):
        return 'RK_PTR'
    if r.startswith('EOS_H'):             return 'RK_PTR'
    if r in ('uint32_t', 'int32_t', 'uint64_t', 'int64_t'):
        return 'RK_INT'
    if r.startswith('EOS_E'):             return 'RK_ENUM'
    return 'RK_INT'

def async_slot(params):
    """Index of the completion-delegate parameter, or -1.

    EOS async entry points always end with (..., void* ClientData, <Callback> CompletionDelegate)."""
    if len(params) < 2:
        return -1
    last = params[-1]
    prev = params[-2]
    if 'Callback' in last and 'void*' in prev.replace(' ', '').replace('const', ''):
        return len(params) - 1
    return -1

def main():
    fns = parse_headers()
    names = [l.strip() for l in open(NAMES, encoding='utf-8') if l.strip()]
    rows, known, unknown = [], 0, 0
    for i, n in enumerate(names):
        info = fns.get(n)
        if info:
            known += 1
            ret, params, hdr = info
            rk = return_kind(ret, n)
            slot = async_slot(params)
            argc = len(params)
            # A notification *registration* looks like an async call (it ends in
            # ClientData + callback) but must never be answered immediately: the
            # handler is retained and invoked when the event actually happens.
            if rk != 'RK_VOID' or '_AddNotify' in n or '_SetNotify' in n:
                slot = -1
        else:
            unknown += 1
            # Undocumented/internal export (EOS_Audio_*, EOS_Mercury_*, ...).
            # Never used by shipping titles; classify conservatively by name.
            rk = 'RK_NOTIFY' if '_AddNotify' in n or n.startswith('EOS_SetNotify') else 'RK_INT'
            slot, argc = -1, 0
        rows.append((i, n, rk, slot, argc))

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('// AUTO-GENERATED by tools/gen_eos_abi.py -- do not edit.\n')
        f.write('// Source: official EOS SDK headers vendored in src/eossdk/sdk/\n')
        f.write('// %d exports, %d described by the SDK headers, %d internal/undocumented.\n\n'
                % (len(rows), known, unknown))
        f.write('REFIX_EOS_EXPORT_TABLE_BEGIN\n')
        for i, n, rk, slot, argc in rows:
            f.write('    REFIX_EOS_EXPORT(%d, "%s", %s, %d, %d)\n' % (i, n, rk, slot, argc))
        f.write('REFIX_EOS_EXPORT_TABLE_END\n')
    print('wrote %s: %d exports (%d from headers, %d internal)' % (OUT, len(rows), known, unknown))

if __name__ == '__main__':
    main()
